---
- hosts: nginx
  become: true

  vars_files:
    - group_vars/nginx/vars.yml

  roles:
    - jdauphant.nginx

- hosts: php
  become: true

  vars_files:
    - group_vars/php/vars.yml

  roles:
    - itcraftsmanpl.php7